// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCamyqFcSwxxCYYCfzTCGpcSC_j3yjMOOg',
    appId: '1:934648548296:web:c12c5dfbc94c58dfdb0efd',
    messagingSenderId: '934648548296',
    projectId: 'my-project-825c1',
    authDomain: 'my-project-825c1.firebaseapp.com',
    storageBucket: 'my-project-825c1.appspot.com',
    measurementId: 'G-V3P2JZN64T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu1IkwS4L76KB71J-2ht-DtSiUGv1oULA',
    appId: '1:934648548296:android:4c50dc7fabd19b24db0efd',
    messagingSenderId: '934648548296',
    projectId: 'my-project-825c1',
    storageBucket: 'my-project-825c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtb67pp1G3tcIeJIK9TBgAn3JA5KSIunA',
    appId: '1:934648548296:ios:0ca65c39e4ad1824db0efd',
    messagingSenderId: '934648548296',
    projectId: 'my-project-825c1',
    storageBucket: 'my-project-825c1.appspot.com',
    iosBundleId: 'com.example.kampusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtb67pp1G3tcIeJIK9TBgAn3JA5KSIunA',
    appId: '1:934648548296:ios:4a06f2c88452f79ddb0efd',
    messagingSenderId: '934648548296',
    projectId: 'my-project-825c1',
    storageBucket: 'my-project-825c1.appspot.com',
    iosBundleId: 'com.example.kampusConnect.RunnerTests',
  );
}
