name: Build Flutter APK

on:
  push:
    branches: [ "staging" ]
  # pull_request:
  #   branches: [ "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9' # Replace with the Flutter version you're using

    - name: Check Flutter environment
      run: flutter doctor -v

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: Kampus-Connect-APK
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: "beta-${{ github.sha:0:8 }}"
        release_name: "Release Beta - ${{ github.sha:0:8 }}"
        body: "Release Notes for this version"
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-release.apk
        asset_name: app-release.apk
        asset_content_type: application/vnd.android.package-archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
